export const CREATE_DOCTOR_REQUEST ='CREATE_DOCTOR_REQUEST'
export const CREATE_DOCTOR_SUCCESS ='CREATE_DOCTOR_SUCCESS'
export const CREATE_DOCTOR_FAIL ='CREATE_DOCTOR_FAIL'
export const CREATE_DOCTOR_RESET='CREATE_DOCTOR_RESET'


export const ADMIN_LOGIN_REQUEST ='ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS ='ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL ='ADMIN_LOGIN_FAIL'
export const ADMIN_LOGIN_RESET='ADMIN_LOGIN_RESET'
export const ADMIN_SIGNOUT='ADMIN_SIGNOUT'


export const GET_ALL_DOCTORS_REQUEST ='GET_ALL_DOCTORS_REQUEST'
export const GET_ALL_DOCTORS_SUCCESS ='GET_ALL_DOCTORS_SUCCESS'
export const GET_ALL_DOCTORS_FAIL ='GET_ALL_DOCTORS_FAIL'

export const ACTIVATE_DOCTOR_REQUEST ='ACTIVATE_DOCTOR_REQUEST'
export const ACTIVATE_DOCTOR_SUCCESS ='ACTIVATE_DOCTOR_SUCCESS'
export const ACTIVATE_DOCTOR_FAIL ='ACTIVATE_DOCTOR_FAIL'
export const ACTIVATE_DOCTOR_RESET='ACTIVATE_DOCTOR_RESET'

export const DEACTIVATE_DOCTOR_REQUEST ='DEACTIVATE_DOCTOR_REQUEST'
export const DEACTIVATE_DOCTOR_SUCCESS ='DEACTIVATE_DOCTOR_SUCCESS'
export const DEACTIVATE_DOCTOR_FAIL ='DEACTIVATE_DOCTOR_FAIL'
export const DEACTIVATE_DOCTOR_RESET='DEACTIVATE_DOCTOR_RESET'


export const GET_ALL_DIET_CHART_REQUEST ='GET_ALL_DIET_CHART_REQUEST'
export const GET_ALL_DIET_CHART_SUCCESS ='GET_ALL_DIET_CHART_SUCCESS'
export const GET_ALL_DIET_CHART_FAIL ='GET_ALL_DIET_CHART_FAIL'


export const GET_ALL_FORMS_REQUEST ='GET_ALL_FORMS_REQUEST'
export const GET_ALL_FORMS_SUCCESS ='GET_ALL_FORMS_SUCCESS'
export const GET_ALL_FORMS_FAIL ='GET_ALL_FORMS_FAIL'