


export const UPLOAD_DIET_CHART_REQUEST ='UPLOAD_DIET_CHART_REQUEST'
export const UPLOAD_DIET_CHART_SUCCESS ='UPLOAD_DIET_CHART_SUCCESS'
export const UPLOAD_DIET_CHART_FAIL ='UPLOAD_DIET_CHART_FAIL'
export const UPLOAD_DIET_CHART_RESET='UPLOAD_DIET_CHART_RESET'


export const CREATE_FORM_REQUEST ='CREATE_FORM_REQUEST'
export const CREATE_FORM_SUCCESS ='CREATE_FORM_SUCCESS'
export const CREATE_FORM_FAIL ='CREATE_FORM_FAIL'
export const CREATE_FORM_RESET='CREATE_FORM_RESET'